# Generated by Django 4.2.6 on 2023-11-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0003_alter_friends_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
