# Generated by Django 4.2.6 on 2023-11-19 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slambook', '0004_alter_friends_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friendOf',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
