# Generated by Django 4.2.6 on 2023-11-20 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friendOf',
        ),
    ]
